### ISSUE TITLE
how to use ``visulization_for_gt``

### ISSUE THREAD

**Issue by Baijiong-Lin** [YuqiYang213/MLoRE#1]
Thanks for your work and code. How to use the ``visulization_for_gt`` function in utils/visualization_utils.py?

**Comment by YuqiYang213** [comment]
Sorry for the late reply.
To call the function `visualization_for_gt`, you can refer to the usage of `vis_phase` in `test_phase` in utils/test_utils.py. The only difference between this and the `visualization_for_gt` is that the former takes the `sample` directly from a dataset with no transforms rather than from a dataloader.
Besides, there are some minor bugs in `visualization_for_gt` in the original code, which have been fixed in the latest version. Please make sure that you are running with the updated code.
I hope this could help.

**Comment by Baijiong-Lin** [comment]
thanks
