### ISSUE TITLE
Many detailed codes are not in accordance with the paper

### ISSUE THREAD

**Issue by Rockyman-star** [YuqiYang213/MLoRE#2]
Thanks for your work! But I found there are some code implementations not consistent with the paper, which are listed in the following.
+ In the paper section **A.1. MLoRE Module Stacking**, you mention that *"Moreover, as the MLoRE is a linear module, we add a task-specific non-linear block between the two MLoRE modules to introduce the nonlinearity into our decoder. Each non-linear block is composed of a GELU-BatchNorm-Linear structure"*. But actually, according to the [MLoRE.py in line 344 to 348](https://github.com/YuqiYang213/MLoRE/blob/c0fff0615498583dc218dcce649577b7e3783e3b/models/transformers/MLoRE.py#L344-L348), the nonlinear block is formed with a **BatchNorm-GELU-Linear** structure.  And it seems that the nonlinear block is inserted both in MLoRE1 and MLoRE2, according to the [MLoRE.py in line 424 to 427](https://github.com/YuqiYang213/MLoRE/blob/c0fff0615498583dc218dcce649577b7e3783e3b/models/transformers/MLoRE.py#L424-L427), **not inserted between MLoRE1 and MLoRE2**. 
+ You don't mention that a extra gate value controls the **Task-specific low-rank expert path**, but it emerges in [MLoRE.py in line 319](https://github.com/YuqiYang213/MLoRE/blob/c0fff0615498583dc218dcce649577b7e3783e3b/models/transformers/MLoRE.py#L319) and [MLoRE.py in line 344](https://github.com/YuqiYang213/MLoRE/blob/c0fff0615498583dc218dcce649577b7e3783e3b/models/transformers/MLoRE.py#L344).
+ In the paper section **2.2. Mixture-of-Experts**, you mention that "*For each task, the output features of MLoRE from different scales are concatenated together to generate the final task features for dense predictions.*" But actually, according to the [MLoRE.py in line 431](https://github.com/YuqiYang213/MLoRE/blob/c0fff0615498583dc218dcce649577b7e3783e3b/models/transformers/MLoRE.py#L431) and [MLoRE.py in line 501 to 504](https://github.com/YuqiYang213/MLoRE/blob/c0fff0615498583dc218dcce649577b7e3783e3b/models/transformers/MLoRE.py#L501-L504), the feature fusion is not a simple concatenation. You use an extra *task_mask* layer to generate probabilities for different scales for each task and leverage the probabilities to weight the features from different scales. This trick may seem very nice, but not consistent with your paper description.
+ In the paper section **3.3. Mixture of Low-Rank Experts**, you mention that "*To be specific, the backbone feature X at the l-th layer is first projected to multiple task splits corresponding to each task using 1 × 1 convolutions*". But actually this is implemented by a sharing 3 x 3 convolution to adjust channels to `final_embed_dim` in [MLoRE.py in line 423](https://github.com/YuqiYang213/MLoRE/blob/c0fff0615498583dc218dcce649577b7e3783e3b/models/transformers/MLoRE.py#L423) and task-specific 1x1 convolutions for each task in [MLoRE.py in line 298](https://github.com/YuqiYang213/MLoRE/blob/c0fff0615498583dc218dcce649577b7e3783e3b/models/transformers/MLoRE.py#L298).
+ ...

Could you please explain why? I don't know whether the inconsistences are resulted by carelessness or other reasons.

**Comment by YuqiYang213** [comment]
Thank you for your interest in our work. 

- For the nonlinear block, we are sorry for the unclear statement. The architecture of the nonlinear block should be BatchNorm-GELU-Linear structure. The statement about block insertion should be "_we add a task-specific non-linear block between the two MLoRE modules and **between the MLoRE modules and the task-specific head**._" All the experiments reported in our paper are based on our code. We apologize for this issue and sincerely thank you for your correction.

- The predicted value for the task-specific low-rank expert path is a scaling value to balance the output feature. We didn't mention this because it's unrelated to our routing algorithm and not the key part of our proposed MLoRE. We will mention it in the updated version of our arxiv in the future.

- For the feature fusing algorithm from different scales, the paper described that "_the output features of MLoRE from different scales are concatenated together **to generate** the final task features_" and didn't dive into the details of "how to generate" the final task features from the concatenated feature. We didn't give a detailed introduction because this is not related to the core part of our idea, which is the mixture of low-rank experts. In addition, we take this algorithm as part of our baseline and all the experiments reported in **ablation** used the same fusing algorithm for fair comparison. We will mention this in the arxiv in the future.

- The convolution used to adjust `final embed dim` is a $1 \times 1$ convolution(not $3 \times 3$ as you mentioned). So the statement that the backbone feature is projected to multiple tasks "_to each task using 1 × 1 convolutions_" is correct. You can check the code in [MLoRE.py in line 423](https://github.com/YuqiYang213/MLoRE/blob/c0fff0615498583dc218dcce649577b7e3783e3b/models/transformers/MLoRE.py#L423).

At last, we sincerely apologize for all the unclear statements in our paper. We will update the arxiv this week to make sure all the missed details are filled and all the errors are corrected.
